# GET Job with ID 43
GET http://localhost:8085/candidates/1
Content-Type: application/json

###

# CREATE Job
POST http://localhost:8085/candidates
Content-Type: application/json

{
  "id": 43,
  "firstName": "محمد",
  "lastName": "المغربي",
  "password": "كلمة السر",
  "email": "example@example.com",
  "address": "شارع النهضة",
  "phone": "+212123456789",
  "gender": "ذكر",
  "city": "الدار البيضاء",
  "profilePic": "URL الصورة الشخصية",
  "bio": "معلومات عن المرشح"
}

###

# UPDATE Job with ID 43
PUT http://localhost:8085/candidates/43
Content-Type: application/json

{
  "firstName": "محمد",
  "lastName": "المغربي",
  "password": "كلمة السر",
  "email": "example@example.com",
  "address": "شارع النهضة",
  "phone": "+212123456789",
  "gender": "ذكر",
  "city": "الدار البيضاء",
  "profilePic": "URL الصورة الشخصية",
  "bio": "معلومات عن المرشح"
}

###

# DELETE Job with ID 43
DELETE http://localhost:8085/candidates/43
Connection: Keep-Alive


###
POST http://localhost:8085/candidatesCount
Content-Type: application/json
